### ISSUE TITLE
CTA dropped on floor after update

### ISSUE THREAD

**Issue by leocg** [isid0re/SoloLeveling#126]
Hi, just a heads up, I gave a mal to bot in town (last rune remaining fot CTA) and wait in game with another char. He went to mausoleum, picked up some items, went back to town, made CTA, identified/sold items to akara, went back to stash and dumped CTA on floor again. At least this time I could pick it up :)

TownOverrides.js:

Town.townTasks = function () {
[...]
Runewords.makeRunewords();
Cubing.doCubing();
Runewords.makeRunewords();
this.equipSWAP();
this.heal();

Town.doChores = function (repair = false) {
[...]
Runewords.makeRunewords();
Cubing.doCubing();
Runewords.makeRunewords();
this.equipSWAP();
this.heal();

**Comment by isid0re** [comment]
Thank you for updating regarding the dropping of the cta. I will try and recreate this scenario. So let me confirm I understood it correctly.

You opened a new game with sololeveling character. (not using d2bitsololevelingentry.dbj)

You entered that game with a mule character and gave a mal rune to sololeveling character.

You then exited the mule game and started a new game using sololevelingentry.dbj

Then the sololeveling character made the cta (skipped equipswap) then ran to a npc to identify etc. And after shopping and equipping items it dropped the cta saying clearjunk.

Is this correct?

**Comment by leocg** [comment]
Yes, he made the CTA skipped equipswap, went to npc to do stuff, went back to stash and dropped the cta. Don't recall if he said clearjunk at the time. The game was made with sololevelingentry.dbj. Char is a hammerdin if that matters

Thanks for all your work, yo

**Comment by isid0re** [comment]
Ahh so you paused the script and loaded the rune then restarted the script. Ok I see what happened. It was a timing mismatch within kolbot Itself. I had that happen when I would pause to test. Its best if you want to load a rune on the bot to instead of pausing and adding to instead enter a game with the character I  question load the bot. Stop the sololeveling profile then start the profile again. That let's the go thru all of its initializing and inventory items check. So something like this wont happen.

**Comment by leocg** [comment]
Ok, thanks for the info! I'll look into that. If I run into this issue again I tell you. cheers!
