### ISSUE TITLE
Inventory lock configuration does not work on low level sorc

### ISSUE THREAD

**Issue by zylo-** [isid0re/SoloLeveling#131]
Hi

I have inventory lock configured but the low level sorc reorganizes the inventory and sells the stuff I didn't want her to sell

**Comment by isid0re** [comment]
Inventory lock is not working with the bot at this time.

**Comment by zylo-** [comment]
ok - may be helpful to add comment in the inventory lock section to mention that - it sold my anni gheeds and torch LOL

**Comment by isid0re** [comment]
I can add the comment in. But remember this is 1 a leveling bot so if you add gear to it you will run the risk of losing it if the bot doesnt like it. And 2 since it's a leveling bot space is a premium and I haven't found a solid way to balance pots and charms and time. So locking inventory puts the bot at risk of failing if the Inventory is filled with charms and it doesnt have room to buy the necessary potions. Also, it will take more time to run back and forth selling items for gold if the inventory is filled with charms. And that's the worst for a leveling bot.

**Comment by zylo-** [comment]
Ahh, that makes sense. Just thought If I threw an anni for the 5-10% exp it would level faster without taking up too much space but it probably doesn't matter. thank you so much for this it's great.
