### ISSUE TITLE
Due to strength issues, the character cannot be equipped with a mon spirit shield?

### ISSUE THREAD

**Issue by wcg928** [isid0re/SoloLeveling#236]
Due to strength issues, the character cannot be equipped with a mon spirit shield?

**Comment by changchangd2** [comment]
You can change the stats in kolbot\libs\SoloLeveling\BuildFiles. For example, the "sorceress.LevelingBuild.js" says on line 16 that she puts in stats in an order of energy until 50, strength until 48, vitality until 165, etc. and then the last strength amount is 84, so once she has 84 strength while leveling, she will not put more strength in. It's also set to max block, so it's going to put a ton of points in dexterity after it has 84 in strength. You could change the strength number to 156 instead of 84 and the bot will put points in until it reaches 156 hard points in strength, not including items. You could change to a vitality build instead of a max block build by deleting the dexterity box completely and it'll put the rest into vitality. I think the creator just has a philosophy preference for leveling and 156 strength for a spirit monarch for a sorc is too high, so they have a moser's blessed circle shield as best while leveling. but you can change it to whatever you want by tweaking the files like that.
