### ISSUE TITLE
pickit

### ISSUE THREAD

**Issue by problemseverywhere** [isid0re/SoloLeveling#259]
hello, where do i put my personal pickit?

**Comment by isid0re** [comment]
You put a pickit in the same way you would with standard kolbot. Under the area labeled pickit configuration.

Just be aware the bot is not designed for farming and magic finding. 

Using a personal pickit you run the risk of 1. Breaking the bot progression cuz it runs out of space and stops or 2. Slows the bot down excessively because it is constantly muling.
