### ISSUE TITLE
Stuck in a loop in act 2

### ISSUE THREAD

**Issue by sqri** [isid0re/SoloLeveling#28]
I've been running the bot as a necromancer and watching it run in a loop for about an hour now. The bot gets stuck in the Maggot Lair trying to skip mobs, goes to town and restarts the routine by going to the waypoint and running through everything again. During "skipping <mob>", the bot keeps spamcasting amp damage or just stands still.

I tried pausing the script, entering the portal manually and then continuing the script, but it would throw an error on useWaypoint and create a new game.

I also noticed that whenever starting a new game, bot goes to countess and apparently fails to kill countess almost immediately after starting the fight, and that it completely skipped quest 5 in act 1.

**Comment by isid0re** [comment]
I've not notived the bot getting abnormally stuck like this. As a fail safe due to kolbots pathing in the maggot lair, the bot will loop 5x if it doesnt have the staff at the start of Duriel. Each time to progress further. I have noticed some issues with kolbots cursing processes as well.  I will look into it further thank you.

**Comment by isid0re** [comment]
There was an issue with the bot attempting to curse maggot eggs from the default kolbot necromancer attacks. It's been corrected in the latest release of sololeveling.
