### ISSUE TITLE
NM Lister - Cold/Fire Immune

### ISSUE THREAD

**Issue by elninost0rm** [isid0re/SoloLeveling#291]
Hello,

Just some feedback based on observation, but I've noticed a cold/fire sorc while MFing in nightmare will just teleport around Lister indefinitely if he has both fire/cold immunities in nightmare.  Eventually the MaxGame is reached, but it was at ~40 minutes of doing that.

Skipping that combo entirely might be advised since I think it wouldn't skip anything else in the game that would prevent progression.

I guess it would need to be slightly customized since normal mob skipping normally means just move on, but obviously you can't since Lister needs to die or be lead away to progress to Baal.

**Comment by tyson-dev** [comment]
I think skipping is the actual thing making you tele around lister instead of letting merc kill ( cause your bot got nowhere to go before Lister is dead ). I Have seen this with my standard bots also and lowered max game time there beacause it's pretty rare i guess. One solution maybe to telestomp immunes which lets merc kill or chicken out.
