### ISSUE TITLE
Need custom picking function

### ISSUE THREAD

**Issue by ircopdd** [isid0re/SoloLeveling#9]
![Ashampoo_Snap_2020年11月21日_09h23m22s_005_](https://user-images.githubusercontent.com/3633003/99863893-49beb800-2bdb-11eb-8e0f-16eecd125b60.png)

BOT didn’t store ZOD in the chest, but took it out as garbage

I lost ZOD

Zod Rune (1)
Can be Inserted into Socketed Items

Weapons: Indestructible
Armor: Indestructible
Helms: Indestructible
Shields: Indestructible

Required Level: 69
Area: Chaos Sanctuary
Line: SoloLeveling #1

**Comment by isid0re** [comment]
Not sure how that happened as the integrated pickit list should be keeping pul thru zod. BUT as a safety check I have added a check to the clearjunkfunction to prevent dropping NTIP wanted items. 

Some file edits to the config will need to be done for custom pickit lists and automuling. To prevent filing mules with leveling items instead of wanted items. But I will add this functionality in a later release. 

For now atleast the check has been put into the script.
